
unique_formname <- reactive({

  unique_formname <- paste0(gsubfn(pattern = ".",
                                   replacement = list("," = "",
                                                      "'" = "",
                                                      "-" = "",
                                                      "." = "",
                                                      " " = "",
                                                      "À" = "A",
                                                      "Á" = "A",
                                                      "Â" = "A",
                                                      "Ä" = "A",
                                                      "Ã" = "A",
                                                      "Å" = "A",
                                                      "Ā" = "A",
                                                      "à" = "a",
                                                      "á" = "a",
                                                      "ã" = "a",
                                                      "â" = "a",
                                                      "ä" = "a",
                                                      "å" = "a",
                                                      "ā" = "a",
                                                      "Č" = "C",
                                                      "Ď" = "D",
                                                      "č" = "c",
                                                      "È" = "E",
                                                      "É" = "E",
                                                      "Ê" = "E",
                                                      "Ë" = "E",
                                                      "Ę" = "E",
                                                      "Ė" = "E",
                                                      "Ē" = "E",
                                                      "è" = "e",
                                                      "é" = "e",
                                                      "ê" = "e",
                                                      "ë" = "e",
                                                      "ę" = "e",
                                                      "ė" = "e",
                                                      "ē" = "e",
                                                      "Ì" = "I",
                                                      "Í" = "I",
                                                      "Ï" = "I",
                                                      "Į" = "I",
                                                      "Ī" = "I",
                                                      "ì" = "i",
                                                      "í" = "i",
                                                      "î" = "i",
                                                      "ï" = "i",
                                                      "į" = "i",
                                                      "ī" = "i",
                                                      "Ñ" = "n",
                                                      "ñ" = "n",
                                                      "Ò" = "O",
                                                      "Ó" = "O",
                                                      "Ô" = "O",
                                                      "Ö" = "O",
                                                      "Õ" = "O",
                                                      "Ø" = "O",
                                                      "Ō" = "O",
                                                      "ò" = "o",
                                                      "ó" = "o",
                                                      "ô" = "o",
                                                      "ö" = "o",
                                                      "õ" = "o",
                                                      "ø" = "o",
                                                      "ō" = "o",
                                                      "Ù" = "U",
                                                      "Ú" = "U",
                                                      "Û" = "U",
                                                      "Ü" = "U",
                                                      "Ū" = "U",
                                                      "ù" = "u",
                                                      "ú" = "u",
                                                      "û" = "u",
                                                      "ü" = "u",
                                                      "ů" = "u",
                                                      "ū" = "u",
                                                      "Ý" = "y",
                                                      "ý" = "y"),
                                   x = input$Author),
                            "_",
                            gsub(pattern = "(?<=\\()[^()]*(?=\\))(*SKIP)(*F)|.",
                                 replacement = "",
                                 x = input$country_study,
                                 perl = T),
                            "_FORM_",
                            sprintf(fmt = "%s%s%s.csv",
                                    as.integer(Sys.time()),
                                    substr(digest::digest(input$author_email),
                                           start = 1,
                                           stop = 5),
                                    digest::digest(input$Author)))

  return(unique_formname)

})

